version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    user: '0:0'
    container_name: sqlserver2019
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Test01.*qw
      MSSQL_PID: Express
    volumes:
      - sqlserver.data:/var/opt/mssql

volumes:
  sqlserver.data: